# Generated by Django 2.1.7 on 2019-03-15 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crypto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(verbose_name='created_at')),
                ('created_by', models.CharField(max_length=20)),
                ('updated_at', models.DateTimeField(verbose_name='updated_at')),
                ('updated_by', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(verbose_name='created_at')),
                ('created_by', models.CharField(max_length=20)),
                ('updated_at', models.DateTimeField(verbose_name='updated_at')),
                ('updated_by', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CurrencyPrice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(verbose_name='created_at')),
                ('created_by', models.CharField(max_length=20)),
                ('updated_at', models.DateTimeField(verbose_name='updated_at')),
                ('updated_by', models.CharField(max_length=20)),
                ('unit', models.CharField(max_length=3)),
                ('price', models.DecimalField(decimal_places=6, max_digits=15)),
                ('low_price', models.DecimalField(decimal_places=6, max_digits=15)),
                ('high_price', models.DecimalField(decimal_places=6, max_digits=15)),
                ('bid_price', models.DecimalField(decimal_places=6, max_digits=15)),
                ('ask_price', models.DecimalField(decimal_places=6, max_digits=15)),
                ('timestamp', models.DateTimeField(verbose_name='timestamp')),
                ('crypto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='default.Crypto')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='default.Currency')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
