# Generated by Django 2.1.7 on 2019-03-15 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0005_auto_20190315_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currencyprice',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='historicalcurrencyprice',
            name='timestamp',
        ),
    ]
